server:
  port: 9001

mybatis:
  configuration:
    cache-enabled: true                            # 二级缓存

spring:
  application:
    name: VHR-REGISTER-SERVICE
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource   # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver       # mysql驱动包
    url: jdbc:mysql://192.168.25.125:3306/vhr      # 数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                                  # 数据库连接池的最小维持连接数
      initial-size: 5                              # 初始化连接数
      max-total: 5                                 # 最大连接数
      max-wait-millis: 200                         # 等待连接获取的最大超时时间

eureka:
  client:                                          # 客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: vhr_service_9001                     # 自定义服务名称信息
    prefer-ip-address: true                        # 访问路径可以显示IP地址


info:
  app.name: vhr
  company.name: www.hzh.com
  build.artifactId: $project.artifactId$,用不了，有时间看看1
  build.version: $project.version$，用不了，有时间看看1
